services:
  riskawareRL:
    container_name: riskawarerl
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    shm_size: '3gb'
    runtime: nvidia
    command: bash -c 'env > /root/.ssh/environment && /usr/sbin/sshd -D'
    image: riskawarerl:latest
    ports:
      - $PORT:10710
    environment:
      - HOME=$HOME
      - USER=$USER
      - NVIDIA_VISIBLE_DEVICES=1
      - CUDA_DEVICE_ORDER=PCI_BUS_ID
    volumes:
      - ${HOME}:${HOME}
      - /data/common/certificates:/certificates
      - ${HOME}/.ssh/authorized_keys:/root/.ssh/authorized_keys
      - /data/$USER:/data
      - /data/$USER/riskawarerl:/workspace 
