#!/usr/bin/env python3
"""
plot_table_comparison.py

Produces a clean grouped-bar comparison plot from the summary table CSV
generated by table_random_settings.py.

Each metric gets its own subplot; bars are grouped by agent.
Error bars show ± SEM (standard error of the mean = std / sqrt(n)).

Example:
  python src/analysis/plot_table_comparison.py \\
      --csv results/table_randomic.csv \\
      --out_dir plots/randomic_settings \\
      --out_prefix comparison
"""
import argparse
import os
import re

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import numpy as np
import pandas as pd


METRICS_WITHIN = [
    # (mean_col, err_col, ylabel, title, hline)
    # err_col uses within-seed SEM (std / sqrt(n_episodes))
    ("success_rate_mean",              "success_rate_sem",              "Success rate",                          "",                      0.95),
    ("cost_total_mean",                "cost_total_sem",                "Mean total cost",                       "",                         15.0),
    ("mean_dist_hazard_success_mean",  "mean_dist_hazard_success_sem",  "Mean distance to hazard (success only)","", None),
]

METRICS_BETWEEN = [
    # (mean_col, err_col, ylabel, title, hline)
    # err_col uses between-seed SEM (std_between / sqrt(n_seeds))
    ("success_rate_between_mean",              "success_rate_between_sem",              "Success rate",                          "",                      0.95),
    ("cost_total_between_mean",                "cost_total_between_sem",                "Mean total cost",                       "",                         15.0),
    ("mean_dist_hazard_success_between_mean",  "mean_dist_hazard_success_between_sem",  "Mean distance to hazard (success only)","", None),
]


def ensure_dir(path: str):
    if path:
        os.makedirs(path, exist_ok=True)


def _penalty_sort_key(name: str):
    """
    Sort agents by penalty value extracted from names like p10, p30, p10_s29.
    Non-numeric names (aggressive, conservative) come first, sorted alphabetically.
    """
    m = re.search(r"p(\d+)", name)
    if m:
        return (1, int(m.group(1)), name)
    return (0, 0, name)


def _get_penalty(name: str):
    m = re.search(r"p(\d+)", str(name))
    return int(m.group(1)) if m else None


# Decade buckets: (label, low_inclusive, high_inclusive)
DECADES = [
    ("p10–p100",   10,    99),
    ("p100–p1k",   100,   999),
    ("p1k–p10k",   1000,  10000),
]


def build_decade_df(df: pd.DataFrame, agents: list,
                    mean_col: str, std_col: str) -> tuple:
    """
    Collapses penalty agents into 3 decade buckets, computing mean ± SEM
    across agents within each decade. Baseline agents are kept as-is.
    Returns (decade_df, ordered_agent_labels).
    """
    baselines      = [a for a in agents if _get_penalty(a) is None]
    penalty_agents = [a for a in agents if _get_penalty(a) is not None]

    rows = []

    # baselines unchanged
    for a in baselines:
        row = df[df["agent"] == a]
        if not row.empty:
            rows.append({
                "agent":   a,
                mean_col:  float(row[mean_col].values[0]) if mean_col in df.columns else float("nan"),
                std_col:   float(row[std_col].values[0])  if std_col  in df.columns else 0.0,
            })

    # aggregate per decade
    for label, lo, hi in DECADES:
        in_decade = [a for a in penalty_agents if lo <= _get_penalty(a) <= hi]
        if not in_decade:
            continue
        vals = []
        for a in in_decade:
            r = df[df["agent"] == a]
            if not r.empty and mean_col in df.columns:
                v = float(r[mean_col].values[0])
                if np.isfinite(v):
                    vals.append(v)
        if not vals:
            continue
        vals = np.array(vals, dtype=np.float64)
        mean_val = float(np.mean(vals))
        sem_val  = float(np.std(vals, ddof=1) / np.sqrt(len(vals))) if len(vals) > 1 else 0.0
        rows.append({"agent": label, mean_col: mean_val, std_col: sem_val})

    decade_df     = pd.DataFrame(rows)
    decade_agents = [r["agent"] for r in rows]
    return decade_df, decade_agents


def plot_single_metric(df: pd.DataFrame, agents: list, label_map: dict,
                       out_path: str, mean_col: str, std_col: str,
                       ylabel: str, title: str, hline, title_prefix: str = ""):
    """Save one bar chart for a single metric."""
    if mean_col not in df.columns:
        print(f"  Skipping {mean_col}: column not found.")
        return

    colors = plt.rcParams["axes.prop_cycle"].by_key()["color"]
    x = np.arange(len(agents))
    bar_width = 0.65

    fig, ax = plt.subplots(figsize=(max(6, len(agents) * 0.9), 5))

    means = []
    stds = []
    for agent in agents:
        row = df[df["agent"] == agent]
        if row.empty:
            means.append(0.0)
            stds.append(0.0)
        else:
            means.append(float(row[mean_col].values[0]))
            stds.append(float(row[std_col].values[0]) if std_col in df.columns else 0.0)

    means = np.asarray(means, dtype=np.float64)
    stds  = np.asarray(stds,  dtype=np.float64)

    agent_colors = [colors[i % len(colors)] for i in range(len(agents))]

    rects = ax.bar(x, means, bar_width, yerr=stds,
                   color=agent_colors, capsize=5,
                   error_kw={"elinewidth": 1.5, "ecolor": "black", "capthick": 1.5},
                   edgecolor="white", linewidth=0.5)

    if hline is not None:
        if "cost" in mean_col:
            hline_label = f"Cost Limit = {hline:.4g}"
        elif "success" in mean_col:
            hline_label = f"Target = {hline:.4g}"
        else:
            hline_label = f"{hline:.4g}"
        ax.axhline(hline, color="red", linestyle="--", linewidth=1.4,
                   label=hline_label, zorder=5)
        ax.legend(fontsize=13, loc="lower right")

    ax.set_xticks(x)
    labels = [label_map.get(a, a) for a in agents]
    ax.set_xticklabels(labels, rotation=30, ha="right", fontsize=9)
    ax.set_ylabel(ylabel, fontsize=10)
    ax.set_title(title, fontsize=11, fontweight="bold", pad=8)
    ax.yaxis.set_major_formatter(mticker.FormatStrFormatter("%.2f"))
    ax.grid(axis="y", linestyle="--", linewidth=0.5, alpha=0.7)
    ax.set_axisbelow(True)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)

    if title_prefix:
        fig.suptitle(title_prefix, fontsize=13, fontweight="bold", y=1.02)

    fig.tight_layout()
    fig.savefig(out_path, dpi=200, bbox_inches="tight")
    plt.close(fig)
    print(f"  Saved: {out_path}")


def plot_comparison(df: pd.DataFrame, agents: list, label_map: dict,
                    out_dir: str, out_prefix: str, title_prefix: str = "",
                    metrics: list = None, by_decade: bool = False):
    if metrics is None:
        metrics = METRICS_WITHIN
    for mean_col, std_col, ylabel, title, hline in metrics:
        suffix = mean_col.replace("_mean", "").replace("_between", "")
        out_path = os.path.join(out_dir, f"{out_prefix}_{suffix}.png")

        if by_decade:
            plot_df, plot_agents = build_decade_df(df, agents, mean_col, std_col)
            plot_label_map = {a: a for a in plot_agents}  # decade labels as-is
        else:
            plot_df, plot_agents, plot_label_map = df, agents, label_map

        plot_single_metric(plot_df, plot_agents, plot_label_map, out_path,
                           mean_col, std_col, ylabel, title, hline,
                           title_prefix=title_prefix)


def main():
    p = argparse.ArgumentParser(
        description="Plot grouped-bar comparison from table_random_settings.py output CSV."
    )
    p.add_argument("--csv", required=True,
                   help="Path to the summary CSV (output of table_random_settings.py).")
    p.add_argument("--agents", nargs="+", default=None,
                   help="Order/subset of agents to show (by name in CSV). "
                        "Defaults to all, in CSV order.")
    p.add_argument("--agent_labels", nargs="+", default=None, metavar="NAME=LABEL",
                   help="Rename agents in plot. E.g. 'Agent 1000=Penalty 1000'.")
    p.add_argument("--title", default="Agent comparison — random budget evaluation",
                   help="Overall figure title.")
    p.add_argument("--out_dir", default="plots",
                   help="Output directory (default: plots).")
    p.add_argument("--out_prefix", default="comparison",
                   help="Output filename prefix (default: comparison).")
    p.add_argument("--between_seed", action="store_true",
                   help="Use between-seed columns (*_between_mean / *_between_sem) "
                        "from aggregate_seeds.py output instead of within-seed columns.")
    p.add_argument("--by_decade", action="store_true",
                   help="Group penalty agents into 3 decades (p10-p100, p100-p1k, p1k-p10k) "
                        "and plot the mean across agents in each decade. Baselines shown separately.")
    p.add_argument("--no_hline", action="store_true",
                   help="Suppress the horizontal safety-budget reference line on cost plots.")
    p.add_argument("--band", choices=["sem", "std"], default="sem",
                   help="Error bar type: 'sem' (default) or 'std'.")
    args = p.parse_args()

    df = pd.read_csv(args.csv)

    if "agent" not in df.columns:
        raise SystemExit("CSV missing 'agent' column.")

    all_agents = list(df["agent"].astype(str).tolist())
    if args.agents:
        agents = [a for a in args.agents if a in all_agents]
    else:
        # auto-sort by penalty value; baselines (non-numeric) come first
        agents = sorted([a for a in all_agents if a in all_agents], key=_penalty_sort_key)
    if not agents:
        raise SystemExit("No agents found.")

    label_map = {}
    if args.agent_labels:
        for entry in args.agent_labels:
            eq = entry.rindex("=")
            label_map[entry[:eq]] = entry[eq + 1:]

    ensure_dir(args.out_dir)

    metrics = METRICS_BETWEEN if args.between_seed else METRICS_WITHIN
    if args.band == "std":
        # replace *_sem columns with the corresponding *_std columns
        metrics = [(mc, sc.replace("_sem", "_std"), yl, ti, hl) for mc, sc, yl, ti, hl in metrics]
    if args.no_hline:
        metrics = [(mc, sc, yl, ti, None) for mc, sc, yl, ti, _ in metrics]
    plot_comparison(df, agents, label_map, args.out_dir, args.out_prefix,
                    title_prefix=args.title, metrics=metrics, by_decade=args.by_decade)
    print(f"\nPlots saved to: {args.out_dir}")


if __name__ == "__main__":
    main()
